### ISSUE TITLE
When you start having wars, your cities will disappear.

### ISSUE THREAD

**Issue by cbbcbail** [EcoGame/Eco#15]
When they come back, they don't have names.

**Comment by phillip-h** [comment]
Possible related to the fact that war can be triggered faster than the update tick runs, causing the real population and the world population to desynchronize.

**Comment by phillip-h** [comment]
Caused by pop auto-balancing, not really a bug.

**Comment by phillip-h** [comment]
Fixed by adding cooldown to pop auto-balance after a war
