### ISSUE TITLE
Server fails to start world (4.2.5 or 4.3)

### ISSUE THREAD

**Issue by JonathanRRose** [EcoGame/Eco#76]
The other day the game updated to 4.3 then downgraded to 4.2.5 again in a short span... I didn't notice anything unusual afterwards, but on restarting my server for 4.3 getting released again, I noticed the world won't start anymore. Same for the 4.2.5 server application when loading from any of my rolling backups...

World file is too big to attach to github, so I'm posting google drive links:
https://drive.google.com/open?id=1wsA3JWQLL3wRvVuWMkOQLgOpTUM-hzac

Also a crash log.

[Crash AggregateException 03292521.zip](https://github.com/EcoGame/eco/files/1859006/Crash.AggregateException.03292521.zip)

I noticed after the downgrade before that the doors had fallen off of all the structures in the world... not sure if that's related, and I did replace the ones on one of the structures.

**Comment by phillip-h** [comment]
I think you have the wrong project here, this is a very very simple game some friends and I made for a class back in high school!

**Comment by JonathanRRose** [comment]
... oops.
